= Purpose

This repository was created to collect multiple different scenarios in which the `org.openapitools:openapi-generator-maven-plugin:6.5.0` does have problems
generating code from a valid OAS 3.0.1 file because of referencing multiple external files.

See https://github.com/OpenAPITools/openapi-generator/issues/15104.

The baseline api is the following open-api file from link:./example-0/open-api.yaml[example-0/open-api.yaml]:

[source,yaml]
----
include::example-0/open-api.yaml[]
----

which does not contain any references!

The following example apis should create exactly the same result:

* `example-0`
* `example-1`
* `example-2`
* `example-4`
* `example-5`

`example-3` only defines `#/components/schemas/paged_stuff_ov1_0` and `#/components/schemas/stuff_ov1_0` is inline defined.

`example-6` is a more simplified version of `example-5` to make debugging easier.

== How to build

[source,bash]
----
./mvnw -fae compile
----

=== Build failures

The following examples fail to build, even though the API is correct:

* example-1
* example-5
* example-6
