openapi: 3.0.3
info:
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt
  title: Swagger API Definition - backend-service - v1
  description: |
    Provides API Services for the integration of backend-service Endpoints (v1)

    <a href="../index.html"><font size=5>Home</font></a>
  version: v1.0
servers:
  - url: https://localhost/services
security:
  - bearer: []
paths:
  /v1.0/stuff:
    $ref: './paths/stuff/ov1.0.yaml'
components:
  responses:
    paged_stuff:
      description: Data of multiple stuffs has been returned successfully (arranged
        alphabetically by stuff name in ascending order).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/paged_stuff_ov1_0'
    400:
      description: |
        Bad Request - The 400 (Bad Request) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    401:
      description: |
        The 401 (Unauthorized) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    403:
      description: |
        Forbidden - The 403 (Forbidden) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    408:
      description: |
        The 408 (Request Timeout) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    429:
      description: |
        Too Many Requests - The 429 (Too Many Requests) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    500:
      description: |
        Internal server error - The 500 (Internal Server Error) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    501:
      description: |
        The 501 (Not Implemented) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
    503:
      description: |
        The 503 (Service Unavailable) status code.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/error_code_ov1_2'
  schemas:
    paged_stuff_ov1_0:
      $ref: './components/schemas/paged_stuff/ov1.0.yaml'
    stuff_ov1_0:
      $ref: './components/schemas/stuff/ov1.0.yaml'
    error_code_ov1_2:
      $ref: './shared-api-spec/components/schemas/error_code/ov1.2.yaml'
  parameters:
    Authorization:
      $ref: './shared-api-spec/components/parameters/header/Authorization/pv1.2.yaml#/Authorization'
    offset:
      $ref: './shared-api-spec/components/parameters/query/offset/pv1.2.yaml#/offset'
    limit:
      $ref: './shared-api-spec/components/parameters/query/limit/pv1.2.yaml#/limit'
    partial_stuff_name:
      name: partial_stuff_name
      in: query
      description: A fragment of the stuff's name of the stuff to search for
        (matches the stuff's name against entered search string of 3
        or more characters).
      required: true
      schema:
        maxLength: 255
        minLength: 3
        pattern: ^[^<>/\\%$&\[\];=]+$
        type: string
  securitySchemes:
    bearer:
      type: apiKey
      description: The Bearer authentication scheme
      name: Authorization
      in: header
